services:
    redis:
        container_name: "redis"
        image: "redis:alpine"
        ports:
          - 6379:6379
    caddy:
        container_name: "caddy"
        build:
          context: ./src/frontend
          dockerfile: Dockerfile
          args:
            APP_URL: http://localhost
            BE_URL: host.docker.internal
        ports:
          - 443:443
          - 80:80
