{
 "title": "Chessmine Monitoring",
 "description": "Docker monitoring with Prometheus and cAdvisor",
 "tags": [ "docker" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Running containers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(container_last_seen{container_label_com_docker_compose_project=\"chessmine\"})"
    }
   ]
  },
  {
   "title": "Total Memory Usage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{container_label_com_docker_compose_project=\"chessmine\"})/1024/1024"
    }
   ]
  },
  {
   "title": "Total CPU Usage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_user_seconds_total{container_label_com_docker_compose_project=\"chessmine\"}[5m]) * 100)"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "rate(container_cpu_user_seconds_total{container_label_com_docker_compose_project=\"chessmine\"}[5m]) * 100",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_usage_bytes{container_label_com_docker_compose_project=\"chessmine\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Caddy req/sec",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 17, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "rate(caddy_http_requests_total{server=\"srv0\"}[1m])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Server moves/sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    { "expr": "rate(moves_played_total[1m])", "legendFormat": "{{instance}}" },
    {
     "expr": "sum(rate(moves_played_total[1m]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Caddy response time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by(code) (rate(caddy_http_response_duration_seconds_count{server=\"srv0\"}[1m]))",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Server move time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by(job) (histogram_quantile(0.99, rate(move_time_bucket{job=\"game_server\"}[5m])))",
     "legendFormat": "99%"
    },
    {
     "expr": "avg by(job) (histogram_quantile(0.9, rate(move_time_bucket{job=\"game_server\"}[5m])))",
     "legendFormat": "90%"
    },
    {
     "expr": "avg by(job) (histogram_quantile(0.5, rate(move_time_bucket{job=\"game_server\"}[5m])))",
     "legendFormat": "50%"
    }
   ]
  },
  {
   "title": "Games Played",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(job) (games_played_total{job=\"game_server\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP status %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(code) (rate(caddy_http_request_duration_seconds_count{server=\"srv0\"}[5m])) / on(method) group_left sum by(handler) (rate(caddy_http_request_duration_seconds_count{server=\"srv0\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}