apiVersion: 1

providers:
- name: General # A uniquely identifiable name for the provider
  folder: Services # The folder where to place the dashboards
  type: file
  options:
    path: /var/lib/grafana/dashboards/dashboard.json
- name: Redis # A uniquely identifiable name for the provider
  folder: Services # The folder where to place the dashboards
  type: file
  options:
    path: /var/lib/grafana/dashboards/redis_dashboard.json