name: chessmine
services:
    redis:
        container_name: "redis"
        build:
          context: ../redis
          dockerfile: Dockerfile
        volumes:
          - ../redis/:/usr/app
        ports:
          - 6379:6379
        deploy:
          resources:
            limits:
              cpus: '0.10'
              memory: 100M
    redis_exporter:
      container_name: "redis_exporter"
      image: "oliver006/redis_exporter:alpine"
      privileged: true
      environment:
        REDIS_ADDR: "redis"
      depends_on:
        - redis
    game_server:
        image: ewr.vultrcr.com/chessmine/game_server:curr
        pull_policy: always
        deploy:
          replicas: 3
          endpoint_mode: dnsrr
          resources:
            limits:
              cpus: '0.30'
              memory: 200M
        build:
          context: ../backend/game_server
          dockerfile: Dockerfile
          tags:
            - "game_server:curr"
        volumes:
          - ../backend/game_server/:/usr/app
        depends_on:
          - redis
    operator:
      image: ewr.vultrcr.com/chessmine/operator:curr
      pull_policy: always
      build:
        context: ../backend/operator
        dockerfile: Dockerfile
        tags:
          - "operator:curr"
      environment:
        SERVER_ADDR: "game_server"
        REDIS_ADDR: "redis"
      volumes:
        - ../backend/operator/:/usr/app
      depends_on:
        - game_server
    caddy:
        container_name: "caddy"
        image: ewr.vultrcr.com/chessmine/frontend:curr
        pull_policy: always
        init: true  # to teardown zombie healthcheck processes
        build:
          context: ../frontend
          dockerfile: Dockerfile
          tags:
            - "frontend:curr"
          args:
            APP_URL: chessmine.xyz
            TLS_CONFIG: chessmine500@protonmail.com
            BE_URL: game_server
        ports:
          - 443:443
          - 80:80
        depends_on:
          - game_server
    cadvisor:
        container_name: "cadvisor"
        image: "gcr.io/cadvisor/cadvisor:latest"
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock:ro
          - /sys:/sys:ro
          - /var/snap/docker/common/var-lib-docker:/var/snap/docker/common/var-lib-docker:ro
        privileged: true
        depends_on:
          - caddy
    prometheus:
        container_name: "prometheus"
        image: "prom/prometheus:latest"
        volumes:
          - ./prometheus.yml:/etc/prometheus/prometheus.yml
          - ./targets.json:/etc/prometheus/targets.json
        privileged: true
        depends_on:
          - cadvisor
    grafana:
        container_name: "grafana"
        image: "grafana/grafana:latest"
        ports:
          - 3000:3000
        environment:
          - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
          - DS_PROMETHEUS=prometheus
        volumes:
          - ./datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
          - ./dashboard.json:/var/lib/grafana/dashboards/dashboard.json
          - ./redis_dashboard.json:/var/lib/grafana/dashboards/redis_dashboard.json
          - ./default.yml:/etc/grafana/provisioning/dashboards/default.yml
        privileged: true
        depends_on:
          - prometheus
