---
name: Basic checks
on:
  pull_request:
    branches:
    - "master"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Run Pylint
        id: pylint
        run:
          python -m pip install --upgrade pip
          pip install pylint
      - name: Analysing the code with pylint
        run:
          pylint $(git ls-files '*.py')
      - name: Test with Checkov
        id: checkov
        uses: bridgecrewio/checkov-action@master
