---
name: Pull Request
on:
  pull_request:
    branches:
    - "master"
permissions: read-all
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install deps
        run: sudo apt-get install -y libcurl4-openssl-dev
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Build
        uses: py-actions/py-dependency-install@30aa0023464ed4b5b116bd9fbdab87acf01a484e
        with:
          path: "src/backend/game_server/requirements.txt"
      - name: Additional Dependencies
        run: pip install websocket-client
      - name: Prepare Lua
        uses: leafo/gh-actions-lua@35bcb06abec04ec87df82e08caa84d545348536e
        with:
          luaVersion: "5.4"
      - name: Luarocks
        uses: leafo/gh-actions-luarocks@e65774a6386cb4f24e293dca7fc4ff89165b64c5
      - name: Install lua modules
        run: |
          luarocks install luacov
          luarocks install luaunit
          luarocks install redis-lua
          luarocks install milua
          luarocks install lunajson
          luarocks install Lua-cURL
      - name: Start Redis
        uses: supercharge/redis-github-action@ea9b21c6ecece47bd99595c532e481390ea0f044
        with:
          redis-version: 7.4.0
      - name: Luacov
        run: lua -lluacov src/backend/game_server/src/lua/test_match.lua
      - name: Start Game Server
        working-directory: src/backend/game_server/
        run: LOG_PATH=server.log REDIS_URL=localhost python src/app.py &
      - name: Start Operator
        working-directory: src/backend/operator/
        run: lua src/app.lua &
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Install NPM dependencies
        working-directory: src/frontend/
        run: npm install
      - name: Test Client Connection
        working-directory: src/frontend/
        run: npm test
      - name: Test Backend
        working-directory: src/backend/game_server/test/
        run: python -m unittest discover -v -s ./  -p 'test_*.py'
      - name: Test with Checkov
        id: checkov
        uses: bridgecrewio/checkov-action@e983355829b735cff43000af6158aac9f7b4a7da
