---
name: Pull Request
on:
  pull_request:
    branches:
    - "master"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Build
        uses: py-actions/py-dependency-install@30aa0023464ed4b5b116bd9fbdab87acf01a484e
        with:
          path: "src/backend/game_server/requirements.txt"
      - name: Prepare Lua
        uses: leafo/gh-actions-lua@35bcb06abec04ec87df82e08caa84d545348536e
        with:
          luaVersion: "5.4"
      - name: Luarocks
        uses: leafo/gh-actions-luarocks@e65774a6386cb4f24e293dca7fc4ff89165b64c5
      - name: Install lua modules
        run: |
          luarocks install redis-lua
      - name: Start Redis
        uses: supercharge/redis-github-action@ea9b21c6ecece47bd99595c532e481390ea0f044
        with:
          redis-version: 7.4.0
      - name: Luacov
        run: |
          lua -lluacov src/backend/game_server/src/lua/test_match.lua
      - name: Test with Checkov
        id: checkov
        uses: bridgecrewio/checkov-action@e983355829b735cff43000af6158aac9f7b4a7da
