---
name: Basic checks
on:
  pull_request:
    branches:
    - "master"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Build
        uses: py-actions/py-dependency-install@30aa002
        with:
          path: "src/backend/game_server/requirements.txt"
      - name: Prepare Lua
      - uses: leafo/gh-actions-lua@35bcb06
        with:
          luaVersion: "5.4"
      - uses: leafo/gh-actions-luarocks@e65774a
      - name: Install lua modules
        run: luarocks install luacheck redis-lua
      - name: lint
        run: |
          for spec in $(find . -type f -name "*.rockspec"); do
            (luarocks lint $spec && echo "$spec [OK]") || (echo "$spec [NOK]"; exit 1);
          done
          luacheck .
      - name: Start Redis
        uses: supercharge/redis-github-action@ea9b21c
        with:
          redis-version: 7.4.0
        run: |
          lua -lluacov test_match.lua
      - name: Test with Checkov
        id: checkov
        uses: bridgecrewio/checkov-action@99bb2ca
